language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no testss"

script:
  - docker --version
  # build containers
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # tag containers
  - docker tag udagram-api-feed lamnt18061999/udagram-api-feed:v4a
  - docker tag udagram-api-user lamnt18061999/udagram-api-user:v4a
  - docker tag udagram-frontend lamnt18061999/udagram-frontend:local
  - docker tag udagram-reverseproxy lamnt18061999/udagram-reverseproxy:v4a

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lamnt18061999/udagram-api-user:v4a
  - docker push lamnt18061999/udagram-api-feed:v4a
  - docker push lamnt18061999/udagram-frontend:local
  - docker push lamnt18061999/udagram-reverseproxy:v4a
  
  - docker pull lamnt18061999/udagram-api-user:v4a
  - docker pull lamnt18061999/udagram-api-feed:v4a
  - docker pull lamnt18061999/udagram-frontend:local
  - docker pull lamnt18061999/udagram-reverseproxy:v4a